config/routes.rb
Rails.application.routes.draw do
  devise_for :users
root to: "users#index"
resources :users,only:[:show]
resources :rooms,only:[:index]
resources :posts do
  resources :comments,only: :create
  get '/likes',to: 'likes#create'
  delete '/likes',to: 'likes#destroy'
  collection do
    get 'search'
  end
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :text,length:{maximum: 50}
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord

  has_many_attached :images,dependent: :destroy
  belongs_to :user
  has_many :comments,dependent: :destroy
  has_many :likes,dependent: :destroy

  validates :text,        presence: { message: 'を入力してください' }
  validates :images,       presence: { message: 'を1枚以上添付してください' }  


  def self.search(keyword)
    if keyword != ""
      Post.where("text LIKE?", "%#{keyword}%") .includes(:user).order('created_at DESC')
    else
      Post.all.includes(:user).order('created_at DESC')
    end 
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
  has_many :likes,dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(params.require(:comment).permit(:text).merge(user_id:current_user.id,post_id:params[:post_id]))
    redirect_to post_path(params[:post_id])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    like = Like.new(params.permit(:post_id).merge(user_id:current_user.id))
    like.save
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    like = Like.find_by(user_id:current_user.id,post_id:params[:post_id])
    like.destroy
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.includes(:user,:comments).order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
   @post = Post.find(params[:id])
   @comment = Comment.new
   @comments = @post.comments.includes(:user).order('created_at DESC')

  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    if post.update(post_params)
      redirect_to post_path(post)
    else
      render :edit
    end
  end

  def search
    @posts = Post.search(params[:keyword])
    render :index
  end
  private

  def post_params
    params.require(:post).permit(:text,images:[]).merge(user_id:current_user.id)
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Original30520</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
<div class="favorite-btn" >
      <% if Like.exists?(user_id:current_user.id,post_id:post.id)%>
        <%= link_to image_tag("heart_ari.png",width:"20",height:"20") ,post_likes_path(post.id),method: :delete,remote: true,class:"fav-btn",id:'favorite-star-icon2' %>
       <% else %>
        <%= link_to image_tag("heart_kara.png",width:"20",height:"20"),post_likes_path(post.id),method: :get ,remote: true, class:"fav-btn" ,id:'favorite-star-icon'%>
      <%end %>
        <span>いいね  <%= Like.where(post_id:post.id).count %></span>
      </div>

app/views/likes/create.js.erb
$('#favorite').html("<%= j(render partial: "likes/like", locals: { post:@post }) %>");

app/views/likes/destroy.js.erb
$('#favorite').html("<%= j(render partial: "likes/like", locals: { post:@post }) %>");

app/views/posts/edit.html.erb
<%= render 'shared/header'%>

<div class="post-new-contents">
  <div class="post-new-main">
    <h2 class="post-new-title">写真の情報を入力</h2>
    <%= form_with model: @post , method: :patch,local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="img-upload">
      <div class="weight-bold-text">
        写真
        <span class="indispensable">必須</span>
      </div>

      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        
        <%= f.file_field :images, multiple: true, id:"photo-image" %>
        <%# <%= f.hidden_field :image,value: @post.images %>
      </div>

      <div id="images-preview">
        <% if @post.images.attached? %>
        <% @post.images.each do |image|%>
        <div class='item-image' >
          <div class=' item-image__content'>
            <div class='item-image__content--icon'>
              <%= image_tag image%>
            </div>
          </div>
          <div class='item-image__operation'>
            <div class='item-image__operation--delete'>削除
            </div>
          </div>
        </div>
        <% end %>
        <% end%>
      </div>
    </div>

    <div class="post-new-photo">
      <div class="photo-explain">
        <div class="weight-bold-text">
          テキスト
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :text, class:"photo-text", id:"photo-info", placeholder:"この画像について説明を書きましょう！" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>

    <div class="post-btn-contents">
      <%= f.submit "更新する" ,class:"post-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
     <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<%= render 'shared/header'%>

<div class="uma-main">

  <div class="uma-top-top">



  <div class="uma-top">

      <div class="uma-title">
        umastagram
      </div>

      <div class="uma-search">
        <%= form_with(url:search_posts_path,local: true,method: :get,class:"search-btn") do |f| %>
          <%= f.text_field :keyword,placeholder:"キーワードを入力" %>
          <%= f.submit "🔍" %>
          <% end %>
      </div>

  </div>

  <div class="new-post">
      <%= link_to image_tag("newphoto.jpg", class: "new-photo"),new_post_path %>
    </div>
  </div>
  
   
    <div class="uma-content-main">
        <% @posts.each do |post|%>
         <div class="uma-content-top"><span></span>
             <%= link_to post.user.nickname,user_path(post),class:'post-user-name'%>
         </div>
         <% post.images.each do |image|%>
         <div class="content-image-boc">
              <%= image_tag image ,class: "content-image" %>
              <% break %>
         </div>
         <% end %>


      <% num = 0%><% comments = post.comments%><% comments.order('created_at DESC').each do |comment|%><% num += 1 %>
      <div class="ume-comment">
        <b><%= link_to comment.user.nickname,user_path(comment.user),class:'comment-user-name' %></b>
        <div class="content-text"><%= comment.text %></div>
         <% if num ==2 %><% break%><% end %>
        
       </div>
       <% end %>
      <div class="ume-comment-details">
        <%= link_to '詳細は画像をクリック',post_path(post) %>
       </div>

    </div>
    <% end %>

</div>

app/views/posts/index2.html.erb
<%= render 'shared/header'%>

<div class="post-contents">
<%# タイトル部分------------- %>
  <div class="post-title-main">
    <div class="new-post">
      <%= link_to image_tag("newphoto.jpg", class: "new-photo"),new_post_path %>
    </div>
    <div class="uma-contents-top">
      <div class="uma-title">umastagram
      </div>
      <div class="uma-search">
        <form method="get" action="#" class="search-btn">
          <input type="text" size="25" placeholder="キーワード検索">
          <input type="submit" value="🔍">
        </form>
      </div>
    </div>
    <div class="profile-img">
    <%= link_to image_tag("典弘.jpg",class: 'post-prf-img'),user_path(current_user) %>
    </div>
  </div>
  </div>
      <%# 画像投稿部分------------ %>
  <div class="uma-contents-bottom">
    <% @posts.each do |post|%>
    <div class="uma-content">
      <div class="uma-content-top"><span></span>
        <%= link_to post.user.nickname,user_path(post),class:'post-user-name'%>
      </div>
      <% post.images.each do |image|%>
      <div class="uma-content-middle">
        <%= image_tag image ,class: "content-image" %>
      </div>
      <% break %>
      <% end %>

      <% num = 0%><% comments = post.comments%><% comments.order('created_at DESC').each do |comment|%><% num += 1 %>
      <div class="ume-comment">
        <div class="comment-one" >
        <b><%= link_to comment.user.nickname,user_path(comment.user),class:'comment-user-name' %></b>
        <%= comment.text %>
      </div>       
      </div>
      <% if num ==2 %><% break%><% end %>
      <% end %>


      <div class="ume-comment-details">
        <%= link_to '詳細は画像をクリック',post_path(post) %>
       </div>
  </div>
  <% end %>
</div>

  
</div>
</footer>

app/views/posts/new.html.erb
<%= render 'shared/header'%>

<div class="post-new-contents">
  <div class="post-new-main">
    <h2 class="post-new-title">写真の情報を入力</h2>
    <%= form_with model: @post , local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="img-upload">
      <div class="weight-bold-text">
        写真
        <span class="indispensable">必須</span>
      </div>

      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :images, multiple: true, id:"photo-image" %>
      </div>
      <div id="images-preview"></div>
       <div id="image-preview">
        <% @post.images.each do |image|%>
         <%= image_tag image.variant(resize: "100x100") %>
      <%end%>
    </div> 
    </div>

    <div class="post-new-photo">
      <div class="photo-explain">
        <div class="weight-bold-text">
          テキスト
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :text, class:"photo-text", id:"photo-info", placeholder:"この画像について説明を書きましょう！" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>

    <div class="post-btn-contents">
      <%= f.submit "投稿する" ,class:"post-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>

  </div>

app/views/posts/show.html.erb
<%= render "shared/header" %>

<div class="item-show">
<%= link_to '戻る',posts_path,class:'back-show-btn' %>
  <div class="item-box">

<% @post.images.each do |image|%>
    <div class='item-img-content'>
      <%= image_tag image ,class:"item-box-img" %>
    </div>
    <% break %><% end %>

 <div class="edit-box">
    <% if @post.user.id == current_user.id %>
    <%= link_to '編集', edit_post_path(@post), method: :get, class: "edit-btn" %>
    <%= link_to '削除', post_path(@post), method: :delete,data: { confirm: '削除しますか？' }, class:'destroy-btn' %>
    <% end  %>
  </div>

    <div class="item-explain-box">
     <b><%= link_to @post.user.nickname,user_path(@post.user) %></b><br>
      <span><%= @post.text %></span>
    </div>
       <div id="favorite">
      <%= render partial: "likes/like", locals: { post:@post } %>
    </div>
  </div>

  <div class="comment-all"><h1>＜コメント一覧＞</h1>
    <% @comments.each do |comment|%>
    <div class="comment-one" >
      <b><%= link_to comment.user.nickname,user_path(comment.user),class:'comment-user-name' %></b>
      <%= comment.text %>
      </div>
      <% end %>
  </div>

  <div class="comment-box">
    <%= form_with model:[@post,@comment],local: true do |f| %>
      <%= f.text_area :text,class:"comment-text"%>
      <div class="comment-box">
      <%= f.submit 'コメントする', class:"comment-btn" %>
      </div>
    <% end %>
  </div>

app/views/rooms/index.html.erb
<%= render 'shared/header'%>

  <div class="room-contents-all">
    <div class="room-contents">
      <h1 class="post-title">うまうま掲示板</h1>
        <h2 class="thread">スレッド一覧</h2>
        <div class="new-room">
        <a href="#" class="new-rooms">新規スレッド作成</a></div>
        <div class="rooms">
          <div class="room">
            <div class="room-title"><a href="#">馬券討論会</a></div>
            <div class="last-create">最終投稿日時:10/19 12:35</div>
          </div>
          <div class="room">
            <div class="room-title"><a href="#">フィエールマンの今後について考える</a></div>
            <div class="last-create">最終投稿日時:10/19 12:35</div>
          </div>
          <div class="room">
            <div class="room-title"><a href="#">横山典弘という男</a></div>
            <div class="last-create">最終投稿日時:10/19 12:35</div>
          </div>
        </div>
    </div>
    </div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
 <div class="header">
  <%= image_tag "mainicon.png" ,class: "header-icon" %><%= link_to "My Derby",root_path,class:"header-title" %>
</div>

app/views/users/index.html.erb
<div class="container">
<div class="row">
    <div class="col span-12">
      <div class="head">
        <div class="head-left">
          <%= image_tag "mainicon.png" ,class: "mainicon" %><%= link_to "My Derby",root_path,class:"title" %>
		</div>
        <div class="head-right">
        <div class="login-box">
          <% if user_signed_in?%>
            <%= link_to "ログアウト",destroy_user_session_path,method: :delete ,class:"logout" %>
          <% else %>
            <%= link_to "新規登録",new_user_registration_path,class:"login"%>
            <%= link_to "ログイン",user_session_path,class:"sign-up"%>
          <% end %>
        </div>
        <div class="snsbox">
			<%= link_to image_tag("in-icon.png"),"https://www.instagram.com/jra.official/" ,class:"instagram"%>
		    <%= link_to image_tag("fb-icon.png"),"https://www.facebook.com/jra",class:"facebook" %>
        </div>
        </div>
    </div>
    </div>
</div>
<div class="row">
    <div class="col span-12">
        <nav>
        <div id="open"><img src="img/button.png"></div>
        <div id="close"><img src="img/button2.png"></div>    
            <div id="navi">
        <ul>
        <% if user_signed_in?%>
            <li><%= link_to "マイページ",user_path(current_user) %></li>
         <% end %>
            <li><%= link_to "Umastagram",posts_path %></li>
            <li><%= link_to "ラップ分析","#" %></li>
            <li><%= link_to "武豊チャレンジ","#" %></li>
            <li><%= link_to "アンケート","#" %></li>
            </ul>
                </div>
        </nav>
    </div>
        </div>
    </div>
    </header>
    <div class="mainimg">
              <%= image_tag "deepimpact.jpg",class:"main_img" %>
        </div>
    <main>
<section>
<div class="container">
	<h2 class="catch">Works</h2>
<div class="row">
	<div class="col span-4">
	<figure>
		<img src="img/catch.jpg" alt="画像">
		<figcaption>キャプション</figcaption>
		</figure>
	</div>
	<div class="col span-4">
	<figure>
		<img src="img/catch.jpg" alt="画像">
		<figcaption>キャプション</figcaption>
		</figure>
	</div>
	<div class="col span-4">
	<figure>
		<img src="img/catch.jpg" alt="画像">
		<figcaption>キャプション</figcaption>
		</figure>
	</div>
    </div>    
<div class="row">
	<div class="col span-4">
	<figure>
		<img src="img/catch.jpg" alt="画像">
		<figcaption>キャプション</figcaption>
		</figure>
	</div>
	<div class="col span-4">
	<figure>
		<img src="img/catch.jpg" alt="画像">
		<figcaption>キャプション</figcaption>
		</figure>
	</div>
	<div class="col span-4">
	<figure>
		<img src="img/catch.jpg" alt="画像">
		<figcaption>キャプション</figcaption>
		</figure>
	</div>
    </div> 
	<p class="center"><button>その他のギャラリー</button></p>
        </div>
</section>
    </main>
    <footer>
<div class="container">
<div class="row">
    <div class="col span-4">
        <h5>フッター１</h5>
        <p>ここにSNSやテキストなどが入ります。SNSやテキストなどが入ります。</p>
    </div>
    <div class="col span-4">
        <h5>フッター２</h5>
        <p>ここにSNSやテキストなどが入ります。SNSやテキストなどが入ります。</p>
    </div>
    <div class="col span-4">
        <h5>フッター３</h5>
        <p>ここにSNSやテキストなどが入ります。SNSやテキストなどが入ります。</p>
    </div>
        </div>
</div>
    </footer>
    <div class="copyright">
<div class="container">
<div class="row">
    <div class="col"><hr>
    Copyright © <a href="https://popo-design.net" target="_blank">popodesign. </a>
    
    </div>    
        </div>
    </div>
        </div>
<p id="pagetop"><a href="#">TOP</a></p>    
</body>
</html>

app/views/users/show.html.erb
<%= render 'shared/header'%>

  <div class="main">
    <div class="user-main">
      <div class="profile-img">
        <img src="典弘.jpg" alt="No image" class="prf-img">
      </div>
      <div class="user-profile">
        <div class="user-profile-top">
        <div class="user-name"><a href="#" class="name"><b>norihiro.yokoyama</b></a></div>
        <div class="user-edit"><a href="#">プロフィールを編集</a> </div>
      </div>
        <div class="user-info">投稿数 170 件</div>
        <div class="user-profile">ノリで〜す。<br>
          52ちゃい<br>
          G1 27勝の天才ジョッキーだよ
        </div>
      </div>
   </div>

   <div class="uma-main">
    <div class="uma-contents-top">
      <div class="uma-title">umastagram
      </div>
    </div>
  </div>

   <div class="user-post-main">
     <div class="post-all"></div>
     <div class="posts">
       <div class="post">
         <img src="ダノンキングリー.png" class="post-img">
       </div>
       <div class="post">
        <img src="ダノンキングリー.png" class="post-img">
      </div>
      <div class="post">
        <img src="ダノンキングリー.png" class="post-img">
      </div>
      <div class="post">
        <img src="ダノンキングリー.png" class="post-img">
     </div>
   </div>
  </div>
</footer>